main: com.ar.askgaming.happyhour.HHPlugin
name: HappyHour
version: 1.6
api-version: 1.21
author: AskGaming
description: HappyHour plugin.
soft-depend: [PlaceholderAPI, Jobs, VotifierPlus]
commands:
  happyhour:
    description: HappyHour command.
    usage: /happyhour
    permission: happyhour.status
    aliases:
    - hh
  challenge:
    description: Challenges command.
    usage: /challenge <start|add> 
    permission: happyhour.challenges
    aliases: [ch, challenges]