main: com.ar.askgaming.happyhour.HHPlugin
name: HappyHour
version: 1.8
api-version: 1.21
author: AskGaming
description: HappyHour plugin.
softdepend: [PlaceholderAPI, Jobs, VotifierPlus]
commands:
  happyhour:
    description: HappyHour command.
    usage: /happyhour
    aliases:
    - hh
  challenge:
    description: Challenges command.
    usage: /challenge <start|add> 
    aliases: [ch, challenges]