#HappyHour
duration_in_minutes: 60

scoreboard:
  enabled: true
  title: "&6&lHappyHour"
  mode: "&7Mode: "
  timeleft: "&7Time left: "
  challenge: "&7Challenge: "
  count: "&7Progress: "

#This will apply to get the random mode
enabled_types:
- MINING
- HUNTING_ANIMALS
- HUNTING_ENEMYS
- WOODCUTTING
- FISHING
- EXPERIENCE
#- JOBS
#- VOTIFIER
#- ALL

scheduler:
  monday:
    "22:00":
    - RANDOM
    #- MINING
    #- FISHING
    #- EXPERIENCE
    #- WOODCUTTING
    #- ANY AVAILABLE MODE
  tuesday:
    "22:00":
    - RANDOM
  wednesday:
    "22:00":
    - RANDOM
  thursday:
    "22:00":
    - RANDOM
  friday:
    "22:00":
    - RANDOM
  saturday:
    "22:00":
    - RANDOM
  sunday:
    "22:00":
    - RANDOM

modes:
  hunting_animals:
    multiplier: 2
    chance: 0.7
  hunting_enemys:
    multiplier: 2
    chance: 0.5
    blacklist_items:
    - TOTEM_OF_UNDYING
    - NETHER_STAR
    - WITHER_SKELETON_SKULL
    - OMINOUS_BOTTLE
    
  experience:
    multiplier: 2
    chance: 0.7
  fishing:
    multiplier: 2
    chance: 0.9
  mining:
    multiplier: 2
    chance: 0.4
    items:
    - DIAMOND
    - EMERALD
    - COAL
    - REDSTONE
    - LAPIS_LAZULI
    - RAW_IRON
    - RAW_GOLD
    - RAW_COPPER
    - GOLD_NUGGET
  woodcutting:
    multiplier: 2
    chance: 0.5
    items:
    - OAK_LOG
    - SPRUCE_LOG
    - BIRCH_LOG
    - JUNGLE_LOG
    - ACACIA_LOG
    - DARK_OAK_LOG
  jobs:
    multiplier: 2
    chance: 0.7
  votifier:
    rewards:
      1: #Example
        chance: 1.0 # 100%
        message: "&6You get extra rewards for voting in happyhour!" #this message will be sended to the player
        commands:
        - eco give %player% 500
      2: #Support multiple rewards
        chance: 0.0 # 0%
        message: ""
        commands: {}
  
